export const COL_DATE = 'Date';
export const COL_TICKER = 'Ticker';
export const COL_TYPE = 'Type';
export const COL_UNITS = 'Units';
export const COL_UNIT_PRICE = 'Unit Price';
export const COL_FEES = 'Fees';
export const COL_NET_TRANSACTION_VALUE = 'Net Transaction Value';

export const TRANSACTION_TYPE_TRF_IN = 'TRF_IN';
export const TRANSACTION_TYPE_TRF_OUT = 'TRF_OUT';
export const TRANSACTION_TYPE_BUY = 'BUY';
export const TRANSACTION_TYPE_SELL = 'SELL';
export const TRANSACTION_TYPE_DRIP = 'DRIP';
export const TRANSACTION_TYPE_STAKE_REWARD = 'STK_RWD';
export const TRANSACTION_TYPE_NON_CASH_DIST = 'NCDIS';
export const TRANSACTION_TYPE_RETURN_OF_CAPITAL = 'ROC';

export const ALL_KNOWN_TRANSACTION_TYPES = [
  TRANSACTION_TYPE_TRF_IN,
  TRANSACTION_TYPE_TRF_OUT,
  TRANSACTION_TYPE_BUY,
  TRANSACTION_TYPE_SELL,
  TRANSACTION_TYPE_DRIP,
  TRANSACTION_TYPE_STAKE_REWARD,
  TRANSACTION_TYPE_NON_CASH_DIST,
  TRANSACTION_TYPE_RETURN_OF_CAPITAL,
];
