const _COL_DATE = 'Date'
const _COL_TICKER = 'Ticker'
const _COL_TYPE = 'Type'
const _COL_ACCOUNT = 'Account'
const _COL_UNITS = 'Units'
const _COL_UNIT_PRICE = 'Unit Price'
const _COL_FEES = 'Fees'
const _COL_NTV = 'Net Transaction Value'

const _TRANSACTION_TYPE_TRF_IN = "TRF_IN";
const _TRANSACTION_TYPE_TRF_OUT = "TRF_OUT";
const _TRANSACTION_TYPE_BUY = "BUY";
const _TRANSACTION_TYPE_SELL = "SELL";
const _TRANSACTION_TYPE_DRIP = "DRIP";
const _TRANSACTION_TYPE_STAKE_REWARD = "STK_RWD";
const _TRANSACTION_TYPE_NON_CASH_DIST = "NCDIS";
const _TRANSACTION_TYPE_RETURN_OF_CAPITAL = "ROC";

const _ALL_KNOWN_TRANSACTION_TYPES = [
  _TRANSACTION_TYPE_TRF_IN,
  _TRANSACTION_TYPE_TRF_OUT,
  _TRANSACTION_TYPE_BUY,
  _TRANSACTION_TYPE_SELL,
  _TRANSACTION_TYPE_DRIP,
  _TRANSACTION_TYPE_STAKE_REWARD,
  _TRANSACTION_TYPE_NON_CASH_DIST,
  _TRANSACTION_TYPE_RETURN_OF_CAPITAL,
];

if (module?.exports) {
  module.exports = {
    _COL_DATE,
    _COL_TICKER,
    _COL_TYPE,
    _COL_ACCOUNT,
    _COL_UNITS,
    _COL_UNIT_PRICE,
    _COL_FEES,
    _COL_NTV,
    _TRANSACTION_TYPE_TRF_IN,
    _TRANSACTION_TYPE_TRF_OUT,
    _TRANSACTION_TYPE_BUY,
    _TRANSACTION_TYPE_SELL,
    _TRANSACTION_TYPE_DRIP,
    _TRANSACTION_TYPE_STAKE_REWARD,
    _TRANSACTION_TYPE_NON_CASH_DIST,
    _TRANSACTION_TYPE_RETURN_OF_CAPITAL,
    _ALL_KNOWN_TRANSACTION_TYPES,
  };
}
